# Generated by Django 5.2.14 on 2026-05-26 03:02

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccessAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('event_type', models.CharField(choices=[('BUSINESS_ACCOUNT_CREATED', 'Business account created'), ('INITIAL_AUTHORISER_ASSIGNED', 'Initial authoriser assigned'), ('INVITATION_ISSUED', 'Invitation issued'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('MEMBER_PROMOTED_TO_AUTHORISER', 'Member promoted to authoriser'), ('MEMBER_REMOVED', 'Member removed'), ('AUTHORISER_REMOVED', 'Authoriser removed'), ('LAST_AUTHORISER_REMOVAL_REJECTED', 'Last authoriser removal rejected')], max_length=64)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('REJECTED', 'Rejected')], default='SUCCESS', max_length=20)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_display_name', models.CharField(max_length=160)),
                ('uen', models.CharField(max_length=32, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('business_display_name',),
            },
        ),
        migrations.CreateModel(
            name='BusinessApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_type', models.CharField(choices=[('BUSINESS_WITHDRAWAL', 'Business withdrawal'), ('BUSINESS_TRANSFER', 'Business transfer')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_type_snapshot', models.CharField(blank=True, max_length=20)),
                ('recipient_identifier_snapshot', models.CharField(blank=True, max_length=80)),
                ('recipient_name_snapshot', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='BusinessInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('intended_role', models.CharField(choices=[('MEMBER', 'Member'), ('AUTHORISER', 'Authoriser')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('AUTHORISER', 'Authoriser')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('business_account__business_display_name', 'user__email'),
            },
        ),
        migrations.CreateModel(
            name='CompletedFinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_DEBIT', 'Transfer debit'), ('TRANSFER_CREDIT', 'Transfer credit'), ('BUSINESS_OPENING_DEPOSIT', 'Business opening deposit')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-completed_at',),
            },
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransferOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-completed_at',),
            },
        ),
    ]
