# Generated by Django 5.2.14 on 2026-05-26 08:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOutgoingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_type', models.CharField(choices=[('BUSINESS_WITHDRAWAL', 'Business withdrawal'), ('BUSINESS_TRANSFER', 'Business transfer')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_type_snapshot', models.CharField(blank=True, max_length=20)),
                ('recipient_identifier_snapshot', models.CharField(blank=True, max_length=80)),
                ('recipient_name_snapshot', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('safe_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='CompletedFinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_DEBIT', 'Transfer debit'), ('TRANSFER_CREDIT', 'Transfer credit'), ('BUSINESS_OPENING_DEPOSIT', 'Business opening deposit')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-completed_at',),
            },
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransferOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-completed_at',),
            },
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_display_name', models.CharField(max_length=160)),
                ('uen', models.CharField(max_length=32, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('business_display_name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='business_account_non_negative_balance')],
            },
        ),
        migrations.CreateModel(
            name='AccessAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('BUSINESS_ACCOUNT_CREATED', 'Business Account created'), ('INITIAL_AUTHORISER_CREATED', 'Initial AUTHORISER created'), ('EMPLOYEE_ACCESS_CREATED', 'Employee access created'), ('TEMPORARY_PASSWORD_ISSUED', 'Temporary password issued'), ('PASSWORD_CHANGE_COMPLETED', 'Password change completed'), ('EMPLOYEE_ACTIVATED', 'Employee activated'), ('TEMPORARY_PASSWORD_RESET', 'Temporary password reset'), ('MEMBER_PROMOTED_TO_AUTHORISER', 'Member promoted to Authoriser'), ('EMPLOYEE_DEACTIVATED', 'Employee deactivated'), ('EMPLOYEE_REACTIVATED', 'Employee reactivated'), ('FINAL_AUTHORISER_DEACTIVATION_REJECTED', 'Final Authoriser deactivation rejected')], max_length=64)),
                ('previous_role', models.CharField(blank=True, max_length=20)),
                ('new_role', models.CharField(blank=True, max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('REJECTED', 'Rejected')], default='SUCCESS', max_length=20)),
                ('safe_metadata', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_audit_events', to='banking.businessaccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BusinessEmployeeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('AUTHORISER', 'Authoriser')], max_length=20)),
                ('access_status', models.CharField(choices=[('PASSWORD_CHANGE_REQUIRED', 'Password Change Required'), ('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('reactivated_at', models.DateTimeField(blank=True, null=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_accesses', to='banking.businessaccount')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_employee_accesses', to='banking.businessemployeeaccess')),
            ],
            options={
                'ordering': ('business_account__business_display_name', 'user__email'),
            },
        ),
    ]
