# Generated by Django 5.2.14 on 2026-05-26 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessemployeeaccess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessauditevent',
            name='acting_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_audit_actions', to='banking.businessemployeeaccess'),
        ),
        migrations.AddField(
            model_name='accessauditevent',
            name='affected_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_audit_subjects', to='banking.businessemployeeaccess'),
        ),
        migrations.AddField(
            model_name='businessoutgoingrequest',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actioned_outgoing_requests', to='banking.businessemployeeaccess'),
        ),
        migrations.AddField(
            model_name='businessoutgoingrequest',
            name='business_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_requests', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessoutgoingrequest',
            name='recipient_business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_business_transfer_requests', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessoutgoingrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_outgoing_requests', to='banking.businessemployeeaccess'),
        ),
        migrations.AddField(
            model_name='completedfinancialtransaction',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_financial_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedfinancialtransaction',
            name='business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_transactions', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='completedfinancialtransaction',
            name='business_outgoing_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_financial_transactions', to='banking.businessoutgoingrequest'),
        ),
        migrations.AddField(
            model_name='businessoutgoingrequest',
            name='completed_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_business_requests', to='banking.completedfinancialtransaction'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedfinancialtransaction',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_transactions', to='banking.personalaccount'),
        ),
        migrations.AddField(
            model_name='businessoutgoingrequest',
            name='recipient_personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_business_transfer_requests', to='banking.personalaccount'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='business_outgoing_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_transfer_operations', to='banking.businessoutgoingrequest'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='recipient_business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_operations', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='recipient_personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_operations', to='banking.personalaccount'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='sender_business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_operations', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='sender_personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_operations', to='banking.personalaccount'),
        ),
        migrations.AddField(
            model_name='completedfinancialtransaction',
            name='transfer_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_transactions', to='banking.transferoperation'),
        ),
        migrations.AddField(
            model_name='businessoutgoingrequest',
            name='transfer_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_outgoing_requests', to='banking.transferoperation'),
        ),
        migrations.AddConstraint(
            model_name='personalaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='personal_account_non_negative_balance'),
        ),
        migrations.AddConstraint(
            model_name='transferoperation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transfer_operation_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='completedfinancialtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='completed_financial_transaction_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='businessoutgoingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='business_outgoing_request_positive_amount'),
        ),
    ]
