# Generated by Django 5.2.14 on 2026-05-25 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='authorised_personal_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_approval_requests', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='business_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='recipient_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_approval_requests', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='approval_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_transactions', to='banking.approvalrequest'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='completed_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_completion', to='banking.completedtransaction'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='recipient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_operations', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='sender_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_operations', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='transfer_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.transferoperation'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='transfer_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='banking.transferoperation'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('owner', 'account_type'), name='one_account_type_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'PERSONAL')), fields=('phone_number',), name='unique_personal_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'BUSINESS')), fields=('uen',), name='unique_business_uen'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='bank_account_non_negative_balance'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_type', 'PERSONAL'), ('authorised_personal_account__isnull', True), ('business_display_name', ''), ('phone_number__isnull', False), ('uen__isnull', True)), models.Q(('account_type', 'BUSINESS'), ('authorised_personal_account__isnull', False), ('business_display_name__gt', ''), ('phone_number__isnull', True), ('uen__isnull', False)), _connector='OR'), name='bank_account_type_specific_fields'),
        ),
    ]
