# Generated by Django 5.2.14 on 2026-05-26 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccessauditevent',
            name='acting_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_access_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessaccessauditevent',
            name='affected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_access_audit_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='businessaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='business_account_non_negative_balance'),
        ),
        migrations.AddField(
            model_name='businessaccessauditevent',
            name='business_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_audit_events', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessapprovalrequest',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actioned_business_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessapprovalrequest',
            name='business_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessapprovalrequest',
            name='recipient_business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_business_transfer_requests', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessapprovalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_business_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_business_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinvitation',
            name='business_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='business_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinvitation',
            name='inviting_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_invitations', to='banking.businessmembership'),
        ),
        migrations.AddField(
            model_name='businessapprovalrequest',
            name='actioning_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actioned_approval_requests', to='banking.businessmembership'),
        ),
        migrations.AddField(
            model_name='businessapprovalrequest',
            name='requesting_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_approval_requests', to='banking.businessmembership'),
        ),
        migrations.AddField(
            model_name='completedfinancialtransaction',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_financial_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedfinancialtransaction',
            name='business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_transactions', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='completedfinancialtransaction',
            name='business_approval_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_financial_transactions', to='banking.businessapprovalrequest'),
        ),
        migrations.AddField(
            model_name='businessapprovalrequest',
            name='completed_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_withdrawal_requests', to='banking.completedfinancialtransaction'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedfinancialtransaction',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_transactions', to='banking.personalaccount'),
        ),
        migrations.AddField(
            model_name='businessapprovalrequest',
            name='recipient_personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_business_transfer_requests', to='banking.personalaccount'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='recipient_business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_operations', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='recipient_personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_operations', to='banking.personalaccount'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='sender_business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_operations', to='banking.businessaccount'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='sender_personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_operations', to='banking.personalaccount'),
        ),
        migrations.AddField(
            model_name='completedfinancialtransaction',
            name='transfer_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_transactions', to='banking.transferoperation'),
        ),
        migrations.AddField(
            model_name='businessapprovalrequest',
            name='transfer_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_approval_requests', to='banking.transferoperation'),
        ),
        migrations.AddConstraint(
            model_name='businessmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('business_account', 'user'), name='one_active_business_membership_per_user_account'),
        ),
        migrations.AddConstraint(
            model_name='businessinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('business_account', 'invited_email'), name='one_pending_invitation_per_email_business'),
        ),
        migrations.AddConstraint(
            model_name='personalaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='personal_account_non_negative_balance'),
        ),
        migrations.AddConstraint(
            model_name='transferoperation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transfer_operation_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='completedfinancialtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='completed_financial_transaction_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='businessapprovalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='business_approval_request_positive_amount'),
        ),
    ]
